### ISSUE TITLE
on mobile this opens up several blank panes, as many links as exist

### ISSUE THREAD

**Issue by brimwats1** [mrjackphil/obsidian-backlinks-in-document#15]
![Screenshot_20210408-115859_Obsidian](https://user-images.githubusercontent.com/49103046/114353025-68d5cc00-9b21-11eb-8029-3d43cf009fa8.jpg)

looks like this

**Comment by mrjackphil** [comment]
@brimwats Latest version should fix the issue. Also, it should look fine in preview mode. 

Can look weird in source mode though. Figuring out how to fix it.

**Comment by mrjackphil** [comment]
Source mode should be fixed as well.
