### ISSUE TITLE
[FEAT] Unordered list, no more content can be displayed

### ISSUE THREAD

**Issue by ghost** [mrjackphil/obsidian-backlinks-in-document#16]
![image](https://user-images.githubusercontent.com/69051504/115124348-4dbcfd80-9ff4-11eb-92bd-9d487ba5b826.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/69051504/115124480-05520f80-9ff5-11eb-81b0-de250289c00e.png)

Can the parent item of an unordered list be displayed like breadcrumbs? (Same as RemNote)

**Comment by mrjackphil** [comment]
@5eagull Thanks for the issue.

It basically the default obsidian panel just placed inside of the document. 

- From the first picture, the only difference between panels (bottom and right) I see is what there is a selected "Show more context" button at the right pane. If you want the panel below to do the same - just select "Show more context there", too.
- About breadcrumbs. I believe it might be done but out of the scope for the current plugin. Maybe in the future, we will see a plugin that will extend the functionality of the backlinks pane.

**Comment by ghost** [comment]
Thank you very much for your reply, I close this issues.
