### ISSUE TITLE
Glitch when opening a new file, and there are no open files. The file doesn't get opened.

### ISSUE THREAD

**Issue by agathauy** [mrjackphil/obsidian-backlinks-in-document#2]
If all of the documents are exited. If one would click at the sidebar the note won't get opened. Although the sidebar visiibly updates for backlinks/table of contents etc.

Tested by turning on and off plugins + restarting Obsidian just to see who's causing this.

Workaround is to press ctrl/cmd + click on the notes from the file explorer sidebar. However, Create New Note or Create New Zettelkasten note won't work.

**Comment by mrjackphil** [comment]
Should be fixed in 0.0.2
