### ISSUE TITLE
Seems that the plugin doesn't work with Obsidian 0.10.1

### ISSUE THREAD

**Issue by xenohunter** [mrjackphil/obsidian-backlinks-in-document#6]
Hey, thank you for a great extension! Sadly, it ceased to work with one of the last updates. I tried to reinstall the plugin, either from the plugin list in Obsidian and manually but it still doesn't work.

**Comment by ybbond** [comment]
I want to inform that I also experienced this issue too.

**Comment by mrjackphil** [comment]
Seems to be the style issue. Hopefully will fix it this weekend.

**Comment by mrjackphil** [comment]
Should be fixed in the latest release.

**Comment by xenohunter** [comment]
@mrjackphil, it works, thank you very much! I guess I'll close the issue then.

**Comment by ybbond** [comment]
Confirmed that this issue has been fixed. Thanks!
