### ISSUE TITLE
Backlinks and unlinked mentions do not show in edit mode

### ISSUE THREAD

**Issue by tallguyjenks** [mrjackphil/obsidian-backlinks-in-document#9]
![image](https://user-images.githubusercontent.com/29872822/108474506-58e9ec00-7244-11eb-90ce-56e37efd9f5e.png)

![image](https://user-images.githubusercontent.com/29872822/108474526-5d160980-7244-11eb-980f-cf60f129a249.png)

---

- Obsidian 0.11.2
- Replicated with the help vault, no custom CSS, no other plugins

**Comment by mrjackphil** [comment]
Hey, @tallguyjenks. Thanks for the issue. Please, try the 0.0.5 version of the plugin. It should be fixed there.

**Comment by tallguyjenks** [comment]
And the linking the unlinked mentions works now too! Fantastic! Thank you!
